#! /bin/sh
#
# System-V init script for isoident
#

CONF_FILE=/media/disk/isoident/isoident.xml
DATASETS=/media/disk/isoident/datasets/
CANLOGGER_CONFIG=/media/disk/canlogger/canlogger.xml

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/etc/conf.d
NAME="isoident"
USER=root

#ISOIDENT_OPTS=" -d ${DATASETS} -f ${CONF_FILE} -g ${CANLOGGER_CONFIG}"
ISOIDENT_OPTS="-c can0 -d ${DATASETS} -f ${CONF_FILE}"
SIGNAL="TERM"
PIPE=">/dev/null 2>/media/disk/isoident/isoident_err.log"

if [ -r ${MMC} ]
then

case "$1" in
start)
	
	echo -n "Starting ${NAME}:"
	
	if (sudo nohup ${NAME} ${ISOIDENT_OPTS} ${PIPE}&) ; then
	echo "done"
	else 
	echo "failed"
	fi
	
	;;
	
stop)   
	${SYNC}

	echo -n "Stopping ${NAME}:"
	
	if  sudo kill -${SIGNAL} ${NAME}  ; then
	echo "done"
	else 
	echo "failed"
	fi
    
	;;
	
restart)

  /etc/init.d/S54isoident stop
  sleep 1
  /etc/init.d/S54isoident start
  
	;;

esac
  else

    	echo "missing sd card"
    	exit 1
  fi
   
exit 0
